lint:
  clang-format:
    included:
      - \.cpp$
      - \.h$
      - \.inl$
      - \.hpp$
    excluded:
      - third_party/
      - scripts/

  cmake-format:
    disabled: true

  copyright:
    excluded:
      - third_party/
    mit_header:
      contents: |-
        {comment_begin}
        {comment_char} Copyright (C) %s Intel Corporation
        {comment_char}
        {comment_char} SPDX-License-Identifier: MIT
        {comment_char}
        {comment_end}
      year_pattern: (\d+)(-\d+)?
      year_constraints:
        _default: 2022
      file_types:
        cpp:
          includes:
            - \.cpp$
            - \.h$
            - \.inl$
            - \.hpp$
            - \.cl$
            - \.m$
            - \.h.in$
            - \.rc.in$
            - ^Jenkinsfile$
          comment_begin: "/*"
          comment_end: >1
            */
          comment_char: " *"
        bash:
          includes:
            - CMakeLists.txt$
            - \.cmake$
            - \.py$
            - \.sh$
          comment_begin: "#"
          comment_char: "#"
        bat:
          includes:
            - \.bat$
            - \.cmd$
          comment_begin: "REM"
          comment_char: "REM"

  ults-needed:
    disabled: true

  binary_files:
    disabled: true
